services:
  - docker

os:
  - linux

before_install:
  - docker pull ubuntu:17.10
  - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/primitiv -td ubuntu:17.10 /bin/bash

install:
  - docker exec travis-ci bash -c "apt update"
  - docker exec travis-ci bash -c "apt install -y build-essential cmake libprotobuf-dev protobuf-compiler googletest python3-dev python3-pip python3-numpy"
  - docker exec travis-ci bash -c "pip3 install cython"

script:
  - docker exec travis-ci bash -c "mkdir /primitiv/result"
  - docker exec travis-ci bash -c "cd /primitiv && cmake . -DPRIMITIV_BUILD_TESTS=ON -DGTEST_SOURCE_DIR=/usr/src/googletest/googletest -DCMAKE_INSTALL_PREFIX=/primitiv/result"
  - docker exec travis-ci bash -c "cd /primitiv && make"
  - docker exec travis-ci bash -c "cd /primitiv && make test"
  - docker exec travis-ci bash -c "cd /primitiv && make install"
  - docker exec travis-ci bash -c "export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH::/primitiv/result/include && export LIBRARY_PATH=$LIBRARY_PATH::/primitiv/result/lib && cd /primitiv/python-primitiv && ./setup.py build"
  - docker exec travis-ci bash -c "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH::/primitiv/result/lib && cd /primitiv/python-primitiv && ./setup.py test"

after_script:
  - docker stop travis-ci
